#!/bin/bash
i3status | while :
do
    read line
    user=`whoami`
    echo "whoami: $user | $line" || exit 1
done
# vnstat -i $(cat /proc/net/wireless | grep ":" | sed -e 's/:.*//g' | sed -e 's/\ //g') --oneline | cut -f 6,11 -d ';'
