
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/local/dev/all/dotfiles/scripts" ] ; then
    PATH="$HOME/local/dev/all/dotfiles/scripts:$PATH"
fi

xsetroot -solid darkred

echo "xinitrc: $0" >> $HOME/user.log

export CONF_FILE_LOADED__XINITRC=1
