
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/local/dev/all/dotfiles/scripts" ] ; then
    PATH="$HOME/local/dev/all/dotfiles/scripts:$PATH"
fi

export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

xsetroot -solid darkred
