#!/bin/bash

# Install Steam.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME="$(readlink -f "${0}")"
SCRIPT_PATH="$(dirname "${SCRIPT_FILENAME}")"
DOTFILES_PATH="${SCRIPT_PATH}/../.."

source "${DOTFILES_PATH}/lib/bivalvia/help.sh"
source "${DOTFILES_PATH}/lib/bivalvia/date.sh"
source "${DOTFILES_PATH}/lib/bivalvia/script-su.sh"
source "${DOTFILES_PATH}/lib/bivalvia/package_management_deb.sh"


# SCRIPT_START_TIMESTAMP="$(timestamp)"
# SCRIPT_START_EPOCH="$(sec_since_epoch)"

STEAM_BASE_PATH="${HOME}/local/bin/steam"
STEAM_TEMP_PATH="${STEAM_BASE_PATH}/temp"
STEAM_INSTALL_PATH="${STEAM_BASE_PATH}/installation"
SUCC_FILENAME="${STEAM_BASE_PATH}/succ"

REQUIRED_DEB_PACKAGE_LIST="build-essential pkg-config libc6-dev libssl-dev libexpat1-dev libavcodec-dev libgl1-mesa-dev libqt4-dev zlib1g-dev"
    

function steam_is_installed {
    local IS_INSTALLED=0

    if [ -d "${STEAM_BASE_PATH}" ]; then
	if [ -f "${SUCC_FILENAME}" ]; then
	    IS_INSTALLED=1
	else
	    echo "Warning: Install path exists but has no success file. Last install attempt failed." >&2
	    echo "Remove all files from previous install attempt." >&2
	    echo "" >&2
	    # rm -rf "${STEAM_BASE_PATH}"
	fi
    fi

    echo ${IS_INSTALLED}
}


function install_steam {
    local STEAM_DOWNLOAD_LINK="https://steamcdn-a.akamaihd.net/client/installer/steam.deb"
    local STEAM_DEB_FILENAME="${STEAM_TEMP_PATH}/steam.deb"
    
    echo "Create temporary directory."
    mkdir -p "${STEAM_TEMP_PATH}"

    echo "Create installation directory."
    mkdir -p "${STEAM_INSTALL_PATH}"

    echo "Download Steam DEB archive."
    # wget -O "${STEAM_DEB_FILENAME}" "${STEAM_DOWNLOAD_LINK}"
    
    echo "Install Steam to ${STEAM_INSTALL_PATH}."
    dpkg -i "${STEAM_DEB_FILENAME}"
    # "${STEAM_INSTALL_PATH}"

    for PACKAGE in ${REQUIRED_DEB_PACKAGE_LIST}; do
	echo "Check if package is installed: ${PACKAGE}"
	if [ $(deb_package_is_installed ${PACKAGE}) -eq 0 ]; then
	    echo "${PACKAGE} is missing. Install as root:"
	    run_as_root "${SCRIPT_FILENAME}" install_packages
	fi
    done

    echo "Mark current installation as successful."
    touch "${SUCC_FILENAME}"
}


function main {
    if [ $(steam_is_installed) -eq 0 ]; then
    	install_steam
    else
	echo "Steam is already installed. To reinstall delete folder \"${STEAM_BASE_PATH}\" first."
    fi
}

main
