#!/bin/bash

# Push a git subtree to a GitHub repository.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME="$(readlink -f "${0}")"
SCRIPT_PATH="$(dirname "${SCRIPT_FILENAME}")"
DOTFILES_PATH="${SCRIPT_PATH}/../.."

source "${DOTFILES_PATH}/lib/bivalvia/help.sh"


git subtree push --prefix=vendor/libbivalvia https://github.com/schanur/libbivalvia.git master
