#!/bin/bash

# Create a new qcow2 virtual machine image with performance optimizations.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
DOTFILES_PATH=${SCRIPT_PATH}/../..

source ${DOTFILES_PATH}/lib/bivalvia/help.sh


function create_qcow2_image_file {
    local HD_IMAGE_NAME=${1}
    local HD_IMAGE_SIZE=${2}

    local EXIT_STATUS
    local CMD

    CMD="qemu-img create                          \
         -f qcow2                                 \
         -o compat=1.1,nocow=on,lazy_refcounts=on \
         ${HD_IMAGE_NAME} ${HD_IMAGE_SIZE}"
    echo ${CMD}
    ${CMD}
    EXIT_STATUS=${?}
    return ${EXIT_STATUS}
}

function main {
    if [ "${#}" -eq "2" ]; then
        create_qcow2_image_file "${@}"
        EXIT_STATUS=$?
        exit ${EXIT_STATUS}
    else
        invalid_parameter_exit
    fi
}

main "${@}"
