#!/bin/bash

# Runs a program with the least possible priority on IO/CPU/etc.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
DOTFILES_PATH=${SCRIPT_PATH}/../..

source ${DOTFILES_PATH}/lib/bivalvia/help.sh


CMD=${*}

IO_BARRIER_DISABLE_CMD="eatmydata"
IONICE_CMD="ionice -c3"
NICE_CMD="nice -n 19"
CHRT_CMD="chrt -i 0"

${IO_BARRIER_DISABLE_CMD} ${IONICE_CMD} ${NICE_CMD} ${CHRT_CMD} ${CMD}
exit ${?}
