#!/bin/bash

# Runs a program with the least possible priority on IO/CPU/etc.

# It currently uses 4 different ways to reduce impact on other programs.
#
# 1) Syncronization directives like sync, fsync, fdatasync, etc. have
#    no effect. This is the only option which is considered
#    dangerous. Therefore it can be disabled with the "--barrier / -b"
#    option
# 2) Set the process to the lowest possible IO class. (ionice -c3)
# 3) Set the nice value to 19
# 4) Set scheduling class to "idle"

set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
DOTFILES_PATH=${SCRIPT_PATH}/../..

source ${DOTFILES_PATH}/lib/bivalvia/help.sh


CMD=${*}

IO_BARRIER_DISABLE_CMD="eatmydata"
IONICE_CMD="ionice -c3"
NICE_CMD="nice -n 19"
CHRT_CMD="chrt -i 0"

${IO_BARRIER_DISABLE_CMD} ${IONICE_CMD} ${NICE_CMD} ${CHRT_CMD} ${CMD}
exit ${?}
