#!/bin/bash

# Runs optipng with slowest settings to archieve maximum PNG file compression.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
DOTFILES_PATH=${SCRIPT_PATH}/../..

source ${DOTFILES_PATH}/lib/bash/help.sh


if [ ${#} != "1" ]; then
    invalid_parameter_exit
fi

optipng -o7 ${1}
