#!/bin/bash

# Create an encrypted partition with LUKS header.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
DOTFILES_PATH=${SCRIPT_PATH}/../..

source ${DOTFILES_PATH}/lib/bash/help.sh
source ${DOTFILES_PATH}/lib/bash/require.sh
source ${DOTFILES_PATH}/lib/bash/script-su.sh


if [ ${#} != "1" ]; then
    invalid_parameter_exit
fi

VIDEO_URL=${1}

require_executable youtube-dl

youtube-dl --extract-audio --format bestaudio ${VIDEO_URL}
