#!/bin/bash


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME="$(readlink -f "${0}")"
SCRIPT_PATH="$(dirname "${SCRIPT_FILENAME}")"
DOTFILES_PATH="${SCRIPT_PATH}/.."


function main {
    # Show failing tests. But allow committing.
    "${DOTFILES_PATH}/test.sh" --exit-success
}

main "${@}"
