#!/bin/bash

# Purge a file from the complete git history by using filter-branch.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME="$(readlink -f "${0}")"
SCRIPT_PATH="$(dirname "${SCRIPT_FILENAME}")"
DOTFILES_PATH="${SCRIPT_PATH}/../.."

source "${DOTFILES_PATH}/lib/bivalvia/help.sh"


FILENAME="${1}"


git filter-branch -f                   \
    --prune-empty                      \
    --tag-name-filter cat              \
    --tree-filter "rm -rf ${FILENAME}" \
    -- --all

git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d
git reflog expire --expire=now --all && git gc --prune=now --aggressive
