#!/bin/bash

# List all git repositories that belong to a username.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME="$(readlink -f "${0}")"
SCRIPT_PATH="$(dirname "${SCRIPT_FILENAME}")"
DOTFILES_PATH="${SCRIPT_PATH}/../.."

source "${DOTFILES_PATH}/lib/bivalvia/help.sh"
source "${DOTFILES_PATH}/lib/bivalvia/git.sh"


function main {
    if [ "${#}" -eq "1" ]; then
        github_repos_by_user ${1}
    else
        invalid_parameter_exit
    fi
}


main "${@}"
