#!/bin/bash

# Link ~/.bashrc to provided bashrc config file of this repository.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME="$(readlink -f "${0}")"
SCRIPT_PATH="$(dirname "${SCRIPT_FILENAME}")"
DOTFILES_PATH="${SCRIPT_PATH}/.."

source "${DOTFILES_PATH}/lib/bivalvia/help.sh"
source "${DOTFILES_PATH}/lib/bivalvia/link.sh"


function main() {
    local LINK_FILENAME_RELATIVE_TO_HOME=".bashrc"
    local DOTFILES_FILENAME="${SCRIPT_PATH}/../bash/bashrc"

    backup_user_config_and_create_dotfiles_link ${DOTFILES_FILENAME} ${LINK_FILENAME_RELATIVE_TO_HOME}
}

main
