#!/bin/bash


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME="$(readlink -f "${0}")"
SCRIPT_PATH="$(dirname "${SCRIPT_FILENAME}")"
DOTFILES_PATH="${SCRIPT_PATH}/.."

source "${DOTFILES_PATH}/lib/bivalvia/help.sh"
source "${DOTFILES_PATH}/lib/bivalvia/link.sh"
source "${DOTFILES_PATH}/lib/bivalvia/config.sh"

source "${DOTFILES_PATH}/lib/shell/install.sh"


function main() {
    local LINK_FILENAME_RELATIVE_TO_HOME=".emacs.d"
    local EMACS_PATH="${DOTFILES_PATH}/vendor/emacs.d"

    if [ ! -d ${EMACS_PATH} ]; then
        echo "No Emacs configuration found. Skip installation"
        exit 0
    fi

    backup_user_config_and_create_dotfiles_link ${EMACS_PATH} ${LINK_FILENAME_RELATIVE_TO_HOME}
}


main
