#!/bin/bash

set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
DOTFILES_PATH=${SCRIPT_PATH}/..

source ${DOTFILES_PATH}/lib/bivalvia/help.sh
source ${DOTFILES_PATH}/lib/bivalvia/link.sh


function main() {
    mkdir -p ${HOME}/.moc
    local LINK_FILENAME_RELATIVE_TO_HOME=".moc/config"
    local DOTFILES_FILENAME="${DOTFILES_PATH}/moc/config"

    backup_user_config_and_create_dotfiles_link ${DOTFILES_FILENAME} ${LINK_FILENAME_RELATIVE_TO_HOME}
}

main
