#!/bin/bash

# Link .profile to provided profile config file of this repository.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
INCLUDE_PATH=${SCRIPT_PATH}/../lib/bash

source ${INCLUDE_PATH}/help.sh
source ${INCLUDE_PATH}/link.sh

function link_dot_profile_to_repo() {
    local HOME_PATH="~"
    local REPO_PATH=${SCRIPT_PATH}/../tmux
    local CMD="ln -s -r ${SCRIPT_PATH}/../profile/profile .profile"

    echo ${CMD}
    ${CMD}
}

function main() {
    local LINK_FILEAME_RELATIVE_TO_HOME=".profile"
    local DOTFILES_FILENAME="${SCRIPT_PATH}/../profile/profile"

    backup_user_config_and_create_dotfiles_link ${DOTFILES_FILENAME} ${LINK_FILEAME_RELATIVE_TO_HOME}
}

main
