#!/bin/bash

# Link .bashrc to provided bashrc config file of this repository.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
INCLUDE_PATH=${SCRIPT_PATH}/../lib/bash

source ${INCLUDE_PATH}/link.sh

function link_dot_profile_to_repo() {
    local HOME_PATH="~"
    local REPO_PATH=${SCRIPT_PATH}/../tmux
    local CMD="ln -s -r ${SCRIPT_PATH}/../profile/profile .profile"

    echo ${CMD}
    ${CMD}
}

function main() {
    link_dot_profile_to_repo
}

main
