#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
INCLUDE_PATH=${SCRIPT_PATH}/../lib/bash

source ${INCLUDE_PATH}/path_variable.sh

# function link_dot_tmux_to_repo() {
#     local HOME_PATH="~"
#     local REPO_PATH=${SCRIPT_PATH}/../tmux
#     local CMD="ln -s -r ${SCRIPT_PATH}/../tmux/tmux.conf .tmux.conf"

#     echo ${CMD}
#     ${CMD}
# }

# function main() {
#     link_dot_tmux_to_repo
# }

# main
echo "Not implemented"
