#!/bin/bash


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME="$(readlink -f "${0}")"
SCRIPT_PATH="$(dirname "${SCRIPT_FILENAME}")"
DOTFILES_PATH="${SCRIPT_PATH}/.."

source "${DOTFILES_PATH}/lib/bivalvia/path_variable.sh"
source "${DOTFILES_PATH}/lib/bivalvia/error.sh"

# function link_dot_tmux_to_repo() {
#     local HOME_PATH="~"
#     local REPO_PATH=${SCRIPT_PATH}/../tmux
#     local CMD="ln -s -r ${SCRIPT_PATH}/../tmux/tmux.conf .tmux.conf"

#     echo ${CMD}
#     ${CMD}
# }

# function main() {
#     link_dot_tmux_to_repo
# }

# main

# not_implemented_error
