#!/bin/bash


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME="$(readlink -f "${0}")"
SCRIPT_PATH="$(dirname "${SCRIPT_FILENAME}")"
DOTFILES_PATH="${SCRIPT_PATH}/.."

source "${DOTFILES_PATH}/lib/bivalvia/help.sh"
source "${DOTFILES_PATH}/lib/bivalvia/link.sh"

source "${DOTFILES_PATH}/lib/shell/install.sh"


function main() {
    local LINK_FILENAME_RELATIVE_TO_HOME
    local DOTFILES_FILENAME

    LINK_FILENAME_RELATIVE_TO_HOME=".config/sway/config"
    DOTFILES_FILENAME="${SCRIPT_PATH}/../sway/config"
    backup_user_config_and_create_dotfiles_link "${DOTFILES_FILENAME}" "${LINK_FILENAME_RELATIVE_TO_HOME}"

    #LINK_FILENAME_RELATIVE_TO_HOME=".config/i3status/config"
    #DOTFILES_FILENAME="${SCRIPT_PATH}/../i3/i3status.conf"
    #backup_user_config_and_create_dotfiles_link "${DOTFILES_FILENAME}" "${LINK_FILENAME_RELATIVE_TO_HOME}"

    LINK_FILENAME_RELATIVE_TO_HOME=".config/i3/custom_i3status"
    DOTFILES_FILENAME="${SCRIPT_PATH}/../i3/custom_i3status"
    backup_user_config_and_create_dotfiles_link "${DOTFILES_FILENAME}" "${LINK_FILENAME_RELATIVE_TO_HOME}"

    LINK_FILENAME_RELATIVE_TO_HOME=".config/i3/toolbox.sh"
    DOTFILES_FILENAME="${SCRIPT_PATH}/../i3/toolbox.sh"
    backup_user_config_and_create_dotfiles_link "${DOTFILES_FILENAME}" "${LINK_FILENAME_RELATIVE_TO_HOME}"
}


main
