#!/bin/bash

# Link ~/.xinitrc to provided xinitrc config file of this repository.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
DOTFILES_PATH=${SCRIPT_PATH}/..

source ${DOTFILES_PATH}/lib/bash/help.sh
source ${DOTFILES_PATH}/lib/bash/link.sh


function main() {
    local LINK_FILEAME_RELATIVE_TO_HOME=".xinitrc"
    local DOTFILES_FILENAME="${SCRIPT_PATH}/../xinit/xinitrc"

    backup_user_config_and_create_dotfiles_link ${DOTFILES_FILENAME} ${LINK_FILEAME_RELATIVE_TO_HOME}
}

main
