#!/bin/bash

# Better defaults for qemu.

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
INCLUDE_PATH=${SCRIPT_PATH}/../lib/bash

# source ${INCLUDE_PATH}/config-file

