#!/bin/bash

# Show the current bitcoin price in US Dollar and Euro.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
DOTFILES_PATH=${SCRIPT_PATH}/..

source ${DOTFILES_PATH}/lib/bash/help.sh


echo "Coinbase:       $(curl -s https://coinbase.com/api/v1/prices/spot_rate      |cut -d '"' -f 4) USD"
echo "BitcoinAverage: $(curl -s https://api.bitcoinaverage.com/ticker/global/EUR/ |grep \"last\" |sed -e 's/.*\:\ //g' |cut -f 1 -d ',') EUR"
