#!/bin/bash

# Create an encrypted partition with LUKS header.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
DOTFILES_PATH=${SCRIPT_PATH}/..

source ${DOTFILES_PATH}/lib/bash/help.sh
source ${DOTFILES_PATH}/lib/bash/require.sh
source ${DOTFILES_PATH}/lib/bash/script-su.sh


run_as_root "${@}"

function create_luks_partition {
    local BLOCK_DEVICE=${1}

    require_block_special ${BLOCK_DEVICE}

    cryptsetup luksFormat    ${BLOCK_DEVICE}     \
        --cipher             twofish-xts-plain64 \
        --key-size           512                 \
        --hash               sha512              \
        --iter-time          5432                \
        --verify-passphrase
}

function main {
    local BLOCK_DEVICE="${@}"

    create_luks_partition ${BLOCK_DEVICE}
}

main "${@}"
