#!/bin/bash

# List all scripts with a short description what they are doing.


set -o errexit -o nounset -o pipefail


SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
INCLUDE_PATH=${SCRIPT_PATH}/../lib/bash

source ${INCLUDE_PATH}/string.sh
source ${INCLUDE_PATH}/help.sh

declare -A GL__SCRIPTS_DESCRIPTION

# GL__SCRIPTS_DESCRIPTION=( ["add-license-file"]="Add a license file to a repository" \
#                                               ["bootstrap_system "]="obsolete")


function list_scripts {
    local ABS_SCRIPT_FILENAME
    local RELATIVE_SCRIPT_FILENAME
    local TABBED_FILENAME
    for ABS_SCRIPT_FILENAME in $(find ${SCRIPT_PATH} |sort); do
        if [ ! -d  ${ABS_SCRIPT_FILENAME} ]; then
            RELATIVE_SCRIPT_FILENAME=$(basename ${ABS_SCRIPT_FILENAME})
            TABBED_FILENAME=$(fill_tail ${RELATIVE_SCRIPT_FILENAME} 28 " ")
            # get_short_description ${ABS_SCRIPT_FILENAME}

            echo "${TABBED_FILENAME}$(short_description ${ABS_SCRIPT_FILENAME})"
        fi
    done
}

function main() {
    list_scripts
}

main
