#!/bin/bash

# Download all files that are linked in a RSS file.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME="$(readlink -f "${0}")"
SCRIPT_PATH="$(dirname "${SCRIPT_FILENAME}")"
DOTFILES_PATH="${SCRIPT_PATH}/.."

source "${DOTFILES_PATH}/lib/bivalvia/help.sh"


FEED_URL=${1}

wget -q -O- "${FEED_URL}" \
| grep -o '<enclosure url="[^"]*' \
| grep -o '[^"]*$' \
| xargs wget -c
