#!/bin/bash

# Return a list of all personal git repositories.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
DOTFILES_PATH=${SCRIPT_PATH}/..

source ${DOTFILES_PATH}/lib/bash/help.sh

# source ${DOTFILES_PATH}/lib/bash/config-file


find ~/local/dev/all -maxdepth 1 -mindepth 1 -type d
