#!/bin/bash

# Change author and committer of multible/all commits of a git repository.


set -o errexit -o nounset -o pipefail


OLD_EMAIL_ADDRESS=${1}
NEW_EMAIL_ADDRESS=${2}
NEW_USERNAME=${3}

FILTER_CMD="git filter-branch --env-filter '
if [ \"\$GIT_COMMITTER_EMAIL\" = \"\${OLD_EMAIL_ADDRESS}\" ]
then
    export GIT_COMMITTER_NAME=\"\${NEW_USERNAME}\"
    export GIT_COMMITTER_EMAIL=\"\${NEW_EMAIL_ADDRESS}\"
fi
if [ \"\$GIT_AUTHOR_EMAIL\" = \"OLD_EMAIL_ADDRESS\" ]
then
    export GIT_AUTHOR_NAME=\"\${NEW_USERNAME}\"
    export GIT_AUTHOR_EMAIL=\"\${NEW_EMAIL_ADDRESS}\"
fi
' --tag-name-filter cat -- --branches --tags"

echo ${FILTER_CMD}
