#!/bin/bash

# List all git repositories that belong to a username.

set -o errexit
set -o nounset
set -o pipefail

function help {
    echo $(basename ${0}) GITHUB_USERNAME
}

function bad_param {
    echo "Wrong number of parameter"
    echo
    help
}

function main {
    if [ "${#}" -eq "1" ]; then
        local USERNAME=${1}
        curl  -s "https://api.github.com/users/${USERNAME}/repos?page=1&per_page=100" |grep html_url |grep "${USERNAME}/" |sed -e "s|.*${USERNAME}/||g" |sed -e "s|\",||g"
    else
        bad_param
    fi
}

main "${@}"
