#!/bin/bash

# Mount preconfigured network shared.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
DOTFILES_PATH=${SCRIPT_PATH}/..

source ${DOTFILES_PATH}/lib/bash/help.sh
source ${DOTFILES_PATH}/lib/bash/script-su.sh


run_as_root

function is_mounted() {
    true
}

function mount_net_share() {
    sshfs -o reconnect,allow_other,ro ${USERNAME}@${HOSTNAME}:${REMOTE_PATH} ${MOUNT_PATH}
}
