#!/bin/bash

# Tunnel all network traffic except this subnet through SSH with the help of sshuttle.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME="$(readlink -f "${0}")"
SCRIPT_PATH="$(dirname "${SCRIPT_FILENAME}")"
DOTFILES_PATH="${SCRIPT_PATH}/.."

source "${DOTFILES_PATH}/lib/bivalvia/help.sh"
source "${DOTFILES_PATH}/lib/bivalvia/script-su.sh"


if [ ${#} != "1" ]; then
    invalid_parameter_exit
fi

GATEWAY_HOSTNAME=${1}

run_as_root "${@}"

echo "GATEWAY_HOSTNAME: ${GATEWAY_HOSTNAME}"

sshuttle --remote="${GATEWAY_HOSTNAME}" 0.0.0.0/0
exit $?

