#!/bin/bash

# Backup home dircetory of current user with bsync.

# Remote backup target is configured in 'config/bsync-home'


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME="$(readlink -f "${0}")"
SCRIPT_PATH="$(dirname "${SCRIPT_FILENAME}")"
DOTFILES_PATH="${SCRIPT_PATH}/.."

source "${DOTFILES_PATH}/lib/bivalvia/help.sh"
source "${DOTFILES_PATH}/lib/bivalvia/config.sh"


HOSTNAME=$(hostname)
USERNAME=$(whoami)
TARGET_PATH_EXTENSION=$(echo ${HOME//\//_} | sed -e 's/^_//g')

load_config_file sync-home.conf
RSYNC_EXCLUDE_FILE=$(absolute_config_file sync-home_exclude.list)

# require_variable RSYNC_HOME__REMOTE_USERNAME
# require_variable RSYNC_HOME__REMOTE_HOST
# require_variable RSYNC_HOME__REMOTE_BASE_PATH

echo "bsync ${HOME} ${RSYNC_HOME__REMOTE_USERNAME}@${RSYNC_HOME__REMOTE_HOST}:${RSYNC_HOME__REMOTE_BASE_PATH}/${HOSTNAME}__${TARGET_PATH_EXTENSION}"

ATTEMPTS=0
MAX_ATTEMPTS=10

while [ 1 ]; do
    (( ATTEMPTS = ATTEMPTS + 1 ))
    echo "Start attempt ${ATTEMPTS}."
    bsync --exclude-from=${RSYNC_EXCLUDE_FILE} ${HOME} ${RSYNC_HOME__REMOTE_USERNAME}@${RSYNC_HOME__REMOTE_HOST}:${RSYNC_HOME__REMOTE_BASE_PATH}/${HOSTNAME}__${TARGET_PATH_EXTENSION}
    SYNC_CMD_EXIT_CODE=${?}
    if [ ${SYNC_CMD_EXIT_CODE} = "0" ]; then
        exit 0
    fi
    if [ ${ATTEMPTS} = ${MAX_ATTEMPTS} ]; then
        echo "Maximum number of attempts (${MAX_ATTEMPTS}) reached."
        exit ${SYNC_CMD_EXIT_CODE}
    fi
done

echo "Successfully synced with ${ATTEMPTS} attempts."
exit 0
