#!/bin/bash

# Run the latest installed Emacs in terminal mode with support for 256 colors.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME="$(readlink -f "${0}")"
SCRIPT_PATH="$(dirname "${SCRIPT_FILENAME}")"
DOTFILES_PATH="${SCRIPT_PATH}/.."

source "${DOTFILES_PATH}/lib/bivalvia/help.sh"


find /usr/bin -name "emacs??" |sort -V

LATEST_AVAILABLE_EMACS_VERSION=$(find /usr/bin -name "emacs??" |sort -V |tail -n 1)
if [ "${LATEST_AVAILABLE_EMACS_VERSION}" = "" ]; then
    # Newer versions of debian skips version numbers in /usr/bin.
    LATEST_AVAILABLE_EMACS_VERSION="emacs"
fi

export TERM=xterm-256color
${LATEST_AVAILABLE_EMACS_VERSION} -nw *$
exit $?
