#!/bin/bash

# Run emacs in terminal mode with support for 256 colors.


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
INCLUDE_PATH=${SCRIPT_PATH}/../lib/bash

source ${INCLUDE_PATH}/help.sh


export TERM=xterm-256color
emacs24 -nw
exit $?
