#!/bin/bash

#

set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
DOTFILES_PATH=${SCRIPT_PATH}/../..

source ${DOTFILES_PATH}/lib/bash/help.sh

#
# git config --global core.gitproxy ~/bin/git-proxy-wrapper
# ssh -f -N -D 8119 -p 443 ${SOCKS_SSH_PROXY}
#
# Tcsh:
#
# setenv GIT_PROXY_COMMAND ~/bin/git-proxy-wrapper
#
# Bash:
#
# export GIT_PROXY_COMMAND=~/bin/git-proxy-wrapper

PARAM_1=${1}
PARAM_2=${1}


PROXY=localhost
PORT=8119


exec socat STDIO SOCKS4:${PROXY}:${PARAM_1}:${PARAM_2},socksport=${PORT}
