#!/bin/bash

# Convert wav file to flac file with presets to produce smallest possible files.

set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME=$(readlink -f $0)
SCRIPT_PATH=$(dirname $SCRIPT_FILENAME)
DOTFILES_PATH=${SCRIPT_PATH}/../..

source ${DOTFILES_PATH}/lib/bash/help.sh


flac --best -e -m $*
