#!/bin/bash

#


set -o errexit -o nounset -o pipefail
SCRIPT_FILENAME="$(readlink -f "${0}")"
SCRIPT_PATH="$(dirname "${SCRIPT_FILENAME}")"
DOTFILES_PATH="${SCRIPT_PATH}/../.."

source "${DOTFILES_PATH}/lib/bivalvia/help.sh"


APPLICATION="${*}"

# Xephyr -ac -resizeable -br -reset -terminate -screen 640x360 2> /dev/null :1 &
Xephyr -ac -resizeable -br -reset -terminate -screen 900x460 2> /dev/null :1 &
sleep 2s
DISPLAY=:1.0

~/local/bin/firefox/firefox/firefox -new-instance -P "overlay"

# DISPLAY=:1.0 && ${APPLICATION}
